version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local_practice
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: